### PR TITLE
Fixing description for leap test 2400 so it matches test

### PR DESCRIPTION
**Pull request by derekgottlieb**
I noticed the test code didn't match the description, so updated it to match.

### CODE REVIEW

**Comment by mhelmetag** [comment]
@derekgottlieb, thanks! Good find! I have to look into this travis error and fix that first but after that I'll pull this.

**Comment by derekgottlieb** [comment]
I tried taking a stab at fixing the travis error. Switched the year params in the example from Int to Int32 and then 'make test' would at least pass on my machine. Now travis errored out hard and looks like it's no longer finding the crystal binary?

**Comment by mhelmetag** [comment]
That might be fixed by a rebuild. I had that happen before.

**Comment by derekgottlieb** [comment]
Going to close and reopen in the hopes it'll kick off another Travis build. Travis ran clean when I tried it on my fork.

**Comment by derekgottlieb** [comment]
Kicking Travis.

**Comment by mhelmetag** [comment]
Nice!!! Thanks!

**Comment by kytrinyx** [comment]
I'm getting a failure on travis regarding Leap on the open pull request #11 - if we're getting intermittent failures I think we need to dig a bit deeper into what's going on.

**Comment by derekgottlieb** [comment]
I'm curious how Travis builds their Docker image for crystal if the binary sometimes gets left out of the build.

**Comment by mhelmetag** [comment]
I saw that `apt` had failed to grab Crystal correctly once before. I think all the Travis image does is just add the binary to `apt` and then download it (just prevents us from having to do that ourselves and use a sudo container).I

I can see if it ends up being more stable to use a sudo container and manually install crystal in the Travis setup.

**Comment by mhelmetag** [comment]
I think the Leap failure is legit though. That one had to do with a change in Crystal that required a more specific type for seconds... I think.

**Comment by kytrinyx** [comment]
Ahh, ok, that makes sense. Thanks @mhelmetag.

**Pull request merged**
