### PR TITLE
Fix extra space in template

### PR DESCRIPTION
**Pull request by bmulvihill**
Removes extra space from generated specs

### CODE REVIEW

**Comment by mhelmetag** [comment]
Curious. So if their no test cases the end will be on the same line as the start? At least that's what the test is saying right now...

```shell
expected: "require \"spec\"\nrequire \"../src/*\"\n\ndescribe \"Dummy\" do\nend\n"
          got: "require \"spec\"\nrequire \"../src/*\"\n\ndescribe \"Dummy\" doend\n"
```

**Comment by bmulvihill** [comment]
Hmm good point, it shouldn't matter because we will always have test cases but Ill take a look again

**Comment by bmulvihill** [comment]
I removed the to_s test because I don't feel it added any value, and now an error will be raised if there are no test_cases

**Comment by mhelmetag** [comment]
Works for me! :+1:

**Pull request merged**
