### PR TITLE
added gigasecond exercise

### PR DESCRIPTION
**Pull request by elorest**
I added the gigasecond exercise from the ruby track. Am I supposed to add a README somewhere?

### CODE REVIEW

**Comment by mhelmetag** [comment]
Awesome! Thanks a bunch!

**Comment by elorest** [comment]
I plan on going through and converting a bunch more in the next couple weeks. Is there anything else I need to do other than what I did last night?

**Comment by mhelmetag** [comment]
Not really. That was perfect.

One thing that would be nice is to verify your tests cases against the ones in the exercise json files found [here](https://github.com/exercism/x-common). Those are usually the gold standard that all tracks' test files are based off of.

Also README's for each exercise are found there as well. Those get downloaded when a user fetches an exercise in any language.

I plan on adding a least one exercise this week as well. I'll pick binary search or binary search tree (so we don't overlap) since I've always wanted to do those in crystal anyways.

**Comment by kytrinyx** [comment]
> I plan on going through and converting a bunch more in the next couple weeks.

Sweet! We have this page to help out: http://exercism.io/languages/crystal/contribute (if the page is confusing, would you mind giving a shout? I'd love to make it easier to convert exercises).

**Pull request merged**
