### PR TITLE
WIP structure exercises to use crystal spec 

### LINKED ISSUE #47: Follow the Crystal convention of placing tests in a spec/ directory
According to the Crystal [Spec module documentation](https://crystal-lang.org/api/0.19.4/Spec.html):

> By convention, specs live in the `spec` directory of a project. You can compile and run the specs of a project by running:
>
> ```
> crystal spec
> ```
>
> Also, you can compile and run individual spec files by providing their path:
>
> ```
> crystal spec spec/my/test/file_spec.cr
> ```
>
> In addition, you can also run individual specs by optionally providing a line number:
>
> ```
> crystal spec spec/my/test/file_spec.cr:14
> ```

Are we interested in following this convention? One reason I'm interested in this is that the excellent [vim-crystal plugin](https://github.com/rhysd/vim-crystal) has keybindings to run specs, but it only works if your project follows the convention of having your spec files in a `spec/` directory.

If we're agreed, I'd be happy to contribute a PR updating the existing exercises.

### PR DESCRIPTION
**Pull request by mhelmetag**
Fixes #47 

More info on that ticket

### CODE REVIEW

**Comment by mhelmetag** [comment]
@daveyarwood , mind taking a look and giving a quick once over? I think we're good...

**Comment by daveyarwood** [comment]
LGTM! 👍

**Comment by mhelmetag** [comment]
Thanks! I'll merge this in after work.

**Comment by mhelmetag** [comment]
Thanks, @daveyarwood !

**Pull request merged**
