### PR TITLE
First stab at adding pangram

### PR DESCRIPTION
**Pull request by derekgottlieb**
First attempt at adding an assignment, so please let me know if I've missed something.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Sweet! This matches the canonical set of tests in https://github.com/exercism/x-common/blob/master/pangram.json so I don't think we're missing any edge cases or anything.

The build is failing... but it's failing on "Leap" which has nothing to do with this. I'll see if I can get whoever dealt with Leap to fix that.

One question about idioms. In Ruby the idiom is to drop the `is_` prefix from predicate methods, since the trailing `?` makes it readable as a question. Does Crystal have any style guides or references that suggest that one or the other is preferable?

**Comment by kytrinyx** [comment]
I'd like the pull request to only have pangram changes in it. Is the second commit the same one as in #10? If so, would you mind rebasing this PR onto the upstream master?

If rebasing is unfamiliar ground, here's one way to do that:

```
git remote add upstream https://github.com/exercism/xcrystal.git
git fetch upstream master
git checkout add-pangram
git rebase upstream/master
git push -fu origin add-pangram
```

**Comment by derekgottlieb** [comment]
I thought I mucked up the git history while trying to rebase. Was hesitant to do the force, but I'll see if I can get that cleaned up and pushed back up. Thanks!

I only started tinkering with Crystal last night, so I'll have to do some searching to see if they have a style guide yet. I'd only gone with is_pangram? since is_leap? was used in the Leap exercise. Will see what I find.

**Comment by kytrinyx** [comment]
Ah, if you do find that they have the same preferences as Ruby `leap?` and `pangram?` vs `is_leap?` and `is_pangram?`, then we'll want to update the leap exercise as well.

**Comment by derekgottlieb** [comment]
The crystal coding style section of their docs is pretty short at this point, so I didn't see any style preference for predicate methods. I did find the following commit from a recent PR that was merged to the core language that would suggest they also prefer to drop the `is_` prefix too:

[Various cleanups #2668](https://github.com/crystal-lang/crystal/pull/2668/commits/f09f1908da8f85a17cec2be812c4f27203b93c85)

Would you prefer I add the  `is_leap?` change in this PR, or open a separate one for that?

**Comment by kytrinyx** [comment]
I'd like to do that in a separate PR.

Thanks for looking into that!

**Comment by kytrinyx** [comment]
I think this looks good, but will leave the final say to @mhelmetag.

Would you mind squashing the commits and making the commit message something like "Implement pangram exercise" or something similar?

**Comment by derekgottlieb** [comment]
Can do!

**Comment by mhelmetag** [comment]
Works for me!

@kytrinyx, thanks for the best practices! I don't think Crystal has a clear styling guide out but since it's so Ruby ish I would warrant a guess that it's not very different.

@derekgottlieb, thanks again for jumping in and helping 😁

**Pull request merged**
